language: bash
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo install shellcheck
  - sudo apt-get install -qq curl
  - sudo bash install.sh

script:
  - sudo bats ./testing.bats
