language: bash

addons:
    #apt:
        sources:
            #- debian-sid
            - sourceline: 'ppa:duggan/bats'
        packages:
            #- shellcheck
            - bats
            - bc

os:
    - linux

script:
- bats ./testing.bats
#- shellcheck bos.sh
