language: bash

addons:
    #apt:
        sources:
            #- debian-sid
            - sourceline: 'ppa:duggan/bats'
        packages:
            - shellcheck
            - apache2
            - curl
            - bats
            - bc

os:
    - linux

script:
- bats ./testing.bats
