---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bos
  name: pvc-bos-file
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
